# Generated by Django 4.0.6 on 2022-07-18 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('sku', models.CharField(max_length=50)),
                ('is_seasonal', models.BooleanField()),
                ('image', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
