# Generated by Django 4.0.6 on 2022-07-19 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_catalogocategoria_products_activo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
