# Generated by Django 4.0.6 on 2022-07-19 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_products_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
    ]
