# Generated by Django 4.0.6 on 2022-07-19 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
    ]
